# Exploring Antibiotic Resistance Trends in *E. coli* Bloodstream Infections in England



## 1. Project Introduction

Antimicrobial resistance (AMR) is an important public health concern because it can make infections more difficult to treat and increase the risk of complications. Monitoring patterns of antibiotic resistance can help healthcare professionals and public health organisations understand the scale of the problem and identify areas that may require further investigation.

This project explores publicly available surveillance data relating to antibiotic resistance in *Escherichia coli* (*E. coli*) bloodstream infections in England. Using data analysis and visualisation, the project aims to examine the patterns and trends represented in the selected dataset and communicate relevant findings clearly.

The project will also consider the ethical responsibilities involved in working with healthcare-related data, including data governance, privacy, responsible interpretation, potential bias and the limitations of the available information.

The intended outcome is an evidence-based analysis supported by appropriate visualisations and a dashboard that communicates findings to a healthcare and public health audience.

## 2. Business Case and Problem Statement

### Business Case

Antimicrobial resistance (AMR) is a significant public health concern because it can reduce the effectiveness of medicines used to treat infections. Monitoring antibiotic resistance helps healthcare professionals and public health organisations understand resistance patterns and identify changes that may require further investigation.

Data analysis and visualisation will be used to explore the information provided by the dataset and communicate relevant findings.

The project aims to demonstrate how data analytics can support public health understanding and evidence-informed decision-making, while recognising that surveillance data alone cannot explain the causes of changes in antibiotic resistance.

### Problem Statement

The central problem addressed by this project is how to present antibiotic resistance surveillance data in a clear and meaningful way so that patterns and changes over time can be explored.

The project will investigate the available data, compare resistance measurements across the antibiotic groups represented in the dataset, and develop visualisations and a dashboard to communicate the findings.

The analysis will also consider data quality, reporting limitations, privacy, responsible interpretation and the ethical responsibilities associated with communicating healthcare-related information.

## 3. Aim, Objectives and Research Questions

### Aim

The aim of this project is to explore antibiotic resistance trends in *Escherichia coli* (*E. coli*) bloodstream infections in England using publicly available UK Health Security Agency (UKHSA) surveillance data.

### Objectives

1. To load, inspect and assess the quality of the selected dataset.
2. To prepare the data for analysis by checking data types, missing values and inconsistencies.
3. To explore antibiotic resistance patterns across the antibiotic groups represented in the dataset.
4. To investigate changes in antibiotic resistance over time, where the available data supports this analysis.
5. To create appropriate visualisations and a dashboard to communicate the findings clearly.
6. To evaluate ethical considerations, data quality, potential bias and limitations when interpreting and communicating the results.

### Research Questions

1. What patterns of antibiotic resistance are represented in the selected *E. coli* bloodstream infection surveillance dataset?
2. How do resistance measurements vary across the antibiotic groups included in the dataset?
3. What changes in antibiotic resistance are observable over time, if the dataset supports a time-based analysis?
4. What data quality issues and ethical considerations should be considered when interpreting and communicating the findings?

## 4. Scope, Intended Audience and Expected Outputs

### Project Scope

The project will cover dataset inspection and preparation, data quality assessment, exploratory data analysis, and visualisation of antibiotic resistance patterns and trends supported by the selected dataset. It will not attempt to establish causal relationships or make clinical predictions beyond what the dataset supports.

### Intended Audience

The intended audience includes healthcare professionals, public health practitioners, researchers and non-technical readers interested in understanding antibiotic resistance trends.

### Expected Outputs

* A prepared and quality-checked dataset.
* A documented data analysis notebook.
* Appropriate visualisations highlighting key findings.
* An interactive dashboard developed using a suitable business intelligence tool.
* A project README documenting the methodology, findings, ethical considerations, limitations and recommendations.

## 5. Dataset Source and Data Governance

### Dataset Source

The project uses a dataset downloaded from the UK Health Security Agency (UKHSA), containing surveillance information on antibiotic resistance in *Escherichia coli* (*E. coli*) bloodstream infections in England. The data will be examined to identify the resistance patterns and trends represented in the available records.

### Data Governance and Responsible Use

The dataset will be used for educational and analytical purposes. Before analysis, its source, available documentation, data structure and quality will be reviewed. The analysis will respect the dataset's stated conditions of use and acknowledge any limitations in the information provided.

The findings will be presented responsibly, avoiding unsupported conclusions about individual patients, causes of resistance or clinical outcomes. Data quality issues and limitations will be documented to support transparent and appropriate interpretation.

# Section 1: Data Inspection and Preparation (ETL)

## 1.1 Python Environment Setup

In [2]:
# Import the modules needed to check the Python environment and working directory
import sys
import os

# Display the Python executable path to verify the active environment
print("Python executable:", sys.executable)

# Display the current working directory
print("Working directory:", os.getcwd())

# Display the Python version in use
print("Python version:", sys.version)

Python executable: c:\Users\kavit\OneDrive\Desktop\Healthcare_Insurance_Assessment2\.venv\Scripts\python.exe
Working directory: c:\Users\kavit\OneDrive\Desktop\Assessment 3\notebooks
Python version: 3.12.10 (tags/v3.12.10:0cc8128, Apr  8 2025, 12:21:36) [MSC v.1943 64 bit (AMD64)]

## 1.2 Import Libraries

In [4]:
# Import libraries required for data analysis and visualisation
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns

# Display the installed versions of the imported libraries
print("Pandas version:", pd.__version__)
print("NumPy version:", np.__version__)
print("Matplotlib version:", matplotlib.__version__)
print("Seaborn version:", sns.__version__)

# Confirm that all libraries have been imported successfully
print("\nLibraries imported successfully.")

Pandas version: 3.0.6
NumPy version: 2.5.3
Matplotlib version: 3.11.2
Seaborn version: 0.13.2

Libraries imported successfully.

## 1.3 Load Dataset and Initial Data Inspection

### Load Dataset

In [5]:
# Load the UKHSA antibiotic resistance dataset from the project data folder
df = pd.read_csv("../data/ukhsa-chart-download.csv")

# Display a confirmation message and the dataset dimensions
print("Dataset loaded successfully.")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

Dataset loaded successfully.
Number of rows: 427
Number of columns: 13

### Initial Data Inspection

The dataset has been loaded successfully. This section examines column names, its structure, sample records, data types and completeness. These checks help us understand the available information and identify potential data quality issues before proceeding with the analysis.

#### Inspect Column Names

The column names identify the information recorded in the dataset. Reviewing them helps us understand the available variables and determine which fields may be useful for analysing antibiotic resistance patterns and trends.

In [6]:
# Display all column names to understand the information available in the dataset
print("Dataset column names:")
print(df.columns.tolist())

Dataset column names:
['theme', 'sub_theme', 'topic', 'geography_type', 'geography', 'metric', 'sex', 'age', 'stratum', 'year', 'date', 'metric_value', 'in_reporting_delay_period']

#### Inspect Sample Records

Displaying the first five rows provides an initial view of the dataset's contents. This helps us understand how the information is organised and see examples of the information recorded in each column.

In [7]:
# Display the first five rows to understand the dataset's structure and contents
df.head()

,theme,sub_theme,topic,geography_type,geography,metric,sex,age,stratum,year,date,metric_value,in_reporting_delay_period
0,infectious_disease,antimicrobial_resistance,E-coli,Nation,England,e-coli_testing_bacteraemiaPercentResistantRoll...,all,all,Amikacin,2026,2026-07-01,2.22,False
1,infectious_disease,antimicrobial_resistance,E-coli,Nation,England,e-coli_testing_bacteraemiaPercentResistantRoll...,all,all,Carbapenems,2026,2026-07-01,0.15,False
2,infectious_disease,antimicrobial_resistance,E-coli,Nation,England,e-coli_testing_bacteraemiaPercentResistantRoll...,all,all,Ciprofloxacin,2026,2026-07-01,20.17,False
3,infectious_disease,antimicrobial_resistance,E-coli,Nation,England,e-coli_testing_bacteraemiaPercentResistantRoll...,all,all,Co-amoxiclav,2026,2026-07-01,43.63,False
4,infectious_disease,antimicrobial_resistance,E-coli,Nation,England,e-coli_testing_bacteraemiaPercentResistantRoll...,all,all,Gentamicin,2026,2026-07-01,12.80,False

#### Inspect Data Types and Completeness

This step examines the data type of each column and checks how many values are present. It helps identify missing data and determine whether columns, such as dates and numerical measurements, may need further preparation before analysis.

In [9]:
# Display each column's data type and the number of non-missing values
# This helps identify missing data and whether columns use appropriate data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 427 entries, 0 to 426
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   theme                      427 non-null    str
 1   sub_theme                  427 non-null    str
 2   topic                      427 non-null    str
 3   geography_type             427 non-null    str
 4   geography                  427 non-null    str
 5   metric                     427 non-null    str
 6   sex                        427 non-null    str
 7   age                        427 non-null    str
 8   stratum                    427 non-null    str
 9   year                       427 non-null    int64
 10  date                       427 non-null    str
 11  metric_value               427 non-null    float64
 12  in_reporting_delay_period  427 non-null    bool
dtypes: bool(1), float64(1), int64(1), str(10)
memory usage: 40.6 KB

#### Check for Duplicate Records

This step checks whether any rows are repeated across all columns. Identifying duplicate records helps assess data quality before analysis. We will review the results before deciding whether any action is necessary.

In [10]:
# Count rows that are exact duplicates across all 13 columns
# This helps identify repeated records before further analysis
print("Number of duplicate rows:", df.duplicated().sum())

Number of duplicate rows: 0

#### Inspect the Date Range

This step examines the earliest and latest dates recorded in the dataset. Understanding the date range helps establish the period covered by the surveillance data and whether it supports analysis of trends over time.

In [11]:
# Convert the date column to datetime format for accurate date analysis
df["date"] = pd.to_datetime(df["date"])

# Display the earliest and latest dates in the dataset
print("Earliest date:", df["date"].min())
print("Latest date:", df["date"].max())

Earliest date: 2021-07-01 00:00:00
Latest date: 2026-07-01 00:00:00

#### Inspect the Expected Date Range

This step checks whether the dataset contains records for every expected reporting period within its date range. Identifying gaps helps us assess data completeness before analysing antibiotic resistance trends over time.

In [12]:
# Create a complete monthly date range between the earliest and latest dates
expected_dates = pd.date_range(
    start=df["date"].min(),
    end=df["date"].max(),
    freq="MS"
)

# Identify dates present in the dataset but missing from the expected monthly range
available_dates = pd.DatetimeIndex(df["date"].unique())
missing_dates = expected_dates.difference(available_dates)

# Display the results of the date completeness check
print("Expected monthly dates:", len(expected_dates))
print("Distinct dates in dataset:", len(available_dates))
print("Missing expected dates:", len(missing_dates))
print("Missing dates:", missing_dates.strftime("%Y-%m-%d").tolist())

Expected monthly dates: 61
Distinct dates in dataset: 61
Missing expected dates: 0
Missing dates: []

#### Inspect Unique Values

This step examines the distinct values recorded in each column. It helps us understand the categories represented in the dataset and identify unexpected or inconsistent values before further analysis.

In [13]:
# Display the number of distinct values in each column
# This helps us understand the categories and variation in the dataset
print("Number of unique values in each column:")
print(df.nunique())

Number of unique values in each column:
theme                          1
sub_theme                      1
topic                          1
geography_type                 1
geography                      1
metric                         1
sex                            1
age                            1
stratum                        7
year                           6
date                          61
metric_value                 348
in_reporting_delay_period      1
dtype: int64

In [14]:
# Display the distinct values in the reporting delay column
print(df["in_reporting_delay_period"].unique())

[False]

#### Inspect Antibiotic Categories

This step identifies the antibiotic categories represented in the dataset. These categories will help us compare resistance measurements during the analysis.

In [15]:
# Display the distinct antibiotic categories in the dataset
print("Antibiotic categories:")
print(sorted(df["stratum"].unique()))

Antibiotic categories:
['Amikacin', 'Carbapenems', 'Ciprofloxacin', 'Co-amoxiclav', 'Gentamicin', 'Piperacillin with tazobactam', 'Third Generation Cephalosporins']

#### Inspect Year Values

This step identifies the years represented in the dataset. It helps confirm the time periods available for analysing changes in antibiotic resistance.

In [16]:
# Display the distinct years in chronological order
print("Years represented in the dataset:")
print(sorted(df["year"].unique()))

Years represented in the dataset:
[np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025), np.int64(2026)]

#### Check for Missing Values

This step counts missing values in each column. It helps identify incomplete data that may need attention before analysis.

In [17]:
# Count missing values in each column
# This helps identify incomplete data that may affect the analysis
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
theme                        0
sub_theme                    0
topic                        0
geography_type               0
geography                    0
metric                       0
sex                          0
age                          0
stratum                      0
year                         0
date                         0
metric_value                 0
in_reporting_delay_period    0
dtype: int64

#### Review Data Types

This step reviews the data types used in the dataset after preparation. The `date` column has been converted from text to `datetime64[us]`, allowing dates to be handled correctly for time-based analysis. This check confirms that the columns use appropriate data types for further analysis.

In [18]:
# Display the current data types of all columns
print("Current data types:")
print(df.dtypes)

Current data types:
theme                                   str
sub_theme                               str
topic                                   str
geography_type                          str
geography                               str
metric                                  str
sex                                     str
age                                     str
stratum                                 str
year                                  int64
date                         datetime64[us]
metric_value                        float64
in_reporting_delay_period              bool
dtype: object

#### Summarise Numerical Resistance Measurements

This step examines the distribution of the numerical values recorded in the `metric_value` column. Summary statistics help us understand the range and distribution of the antibiotic resistance measurements before proceeding with further data quality checks and analysis.

In [19]:
# Calculate summary statistics for the numerical resistance measurements
# These statistics show the count, mean, standard deviation, quartiles and range
print("Summary statistics for numerical resistance measurements:")
print(df["metric_value"].describe())

Summary statistics for numerical resistance measurements:
count    427.000000
mean      14.854848
std       13.020515
min        0.100000
25%        3.195000
50%       12.460000
75%       18.285000
max       45.510000
Name: metric_value, dtype: float64

**Initial observations:** The `metric_value` column contains 427 numerical values, with a minimum of 0.10, a maximum of 45.51, and a median of 12.46. The mean is 14.85, which is higher than the median. These summary statistics describe the overall distribution of the recorded values; further analysis is needed to compare measurements across antibiotic categories and time periods.

#### Inspect Records by Antibiotic and Date

This step examines how many records are available for each antibiotic category and reporting date. It helps us understand the dataset's structure and identify whether any antibiotic categories have multiple records for the same date.

In [21]:
# Count the number of records for each antibiotic category and reporting date
records_per_antibiotic_date = df.groupby(
    ["stratum", "date"]
).size()

# Display summary statistics for the number of records per antibiotic and date
print("Summary of records per antibiotic and date:")
print(records_per_antibiotic_date.describe())

# Display the number of antibiotic-date combinations with more than one record
print(
    "\nAntibiotic-date combinations with multiple records:",
    (records_per_antibiotic_date > 1).sum()
)

Summary of records per antibiotic and date:
count    427.0
mean       1.0
std        0.0
min        1.0
25%        1.0
50%        1.0
75%        1.0
max        1.0
dtype: float64

Antibiotic-date combinations with multiple records: 0

**Initial observations:** The dataset contains 427 antibiotic-date combinations, with one record for each combination. No duplicate combinations were identified. This indicates that each antibiotic category has at most one recorded measurement for each reporting date in the dataset.

#### Inspect Record Counts by Antibiotic

This step counts the records available for each antibiotic category. Comparing these counts helps us assess whether the dataset contains a similar number of observations for each category.

In [22]:
# Count the number of records available for each antibiotic category
records_per_antibiotic = df["stratum"].value_counts().sort_index()

# Display the record count for each antibiotic category
print("Number of records per antibiotic category:")
print(records_per_antibiotic)

Number of records per antibiotic category:
stratum
Amikacin                           61
Carbapenems                        61
Ciprofloxacin                      61
Co-amoxiclav                       61
Gentamicin                         61
Piperacillin with tazobactam       61
Third Generation Cephalosporins    61
Name: count, dtype: int64

**Initial observations:** Each of the seven antibiotic categories contains 61 records. The record counts are therefore balanced across the categories, with each category represented by the same number of observations. However, equal record counts alone do not confirm that every category has complete or comparable data for all reporting periods.

#### Check Monthly Coverage by Antibiotic

This step checks whether each antibiotic category has a record for every expected reporting date. Although the dataset contains all 61 distinct reporting dates overall, this check will establish whether those dates are represented for every antibiotic category.

In [23]:
# Count the distinct reporting dates recorded for each antibiotic category
dates_per_antibiotic = df.groupby("stratum")["date"].nunique().sort_index()

# Display the number of distinct reporting dates for each antibiotic
print("Distinct reporting dates per antibiotic category:")
print(dates_per_antibiotic)

# Check whether each antibiotic has all 61 expected reporting dates
expected_date_count = len(expected_dates)
print("\nExpected reporting dates per antibiotic:", expected_date_count)
print(
    "Antibiotics with fewer than expected dates:",
    (dates_per_antibiotic < expected_date_count).sum()
)

Distinct reporting dates per antibiotic category:
stratum
Amikacin                           61
Carbapenems                        61
Ciprofloxacin                      61
Co-amoxiclav                       61
Gentamicin                         61
Piperacillin with tazobactam       61
Third Generation Cephalosporins    61
Name: date, dtype: int64

Expected reporting dates per antibiotic: 61
Antibiotics with fewer than expected dates: 0

**Initial observations:** Each of the seven antibiotic categories contains records for all 61 expected reporting dates, covering July 2021 to July 2026. No gaps were identified in the monthly date coverage for any category. This supports consistent time-based comparisons across the antibiotic categories, although other aspects of data quality still need to be assessed.

#### Check the Numerical Measurement Range

This step checks whether any values in the `metric_value` column fall outside the range of 0 to 100. As the dataset's metric name refers to the percentage of resistant isolates, this check can help identify potentially invalid values. The interpretation will be confirmed against the dataset's documentation.

In [24]:
# Identify measurements below 0 or above 100
# These values would fall outside the usual range for percentages
invalid_values = df[
    (df["metric_value"] < 0) | (df["metric_value"] > 100)
]

# Display the number of values outside the expected percentage range
print("Measurements outside the 0–100 range:", len(invalid_values))

# Display any records requiring further investigation
print(invalid_values[["stratum", "date", "metric_value"]])

Measurements outside the 0–100 range: 0
Empty DataFrame
Columns: [stratum, date, metric_value]
Index: []

**Initial observations:** No measurements fall below 0 or above 100. All recorded values are therefore within the expected numerical range for percentages. However, this check alone does not establish that every measurement is accurate or valid.

## 1.4 Data Quality Assessment and Preparation

This section assesses the dataset for potential data quality issues and identifies whether any preparation is needed before exploratory data analysis.

### Checking Categorical Values

This step examines the unique values in the categorical columns to identify unexpected labels or inconsistencies before further data preparation.

In [25]:
# Display unique values in categorical columns to check for inconsistencies.

categorical_columns = [
    "theme",
    "sub_theme",
    "topic",
    "geography_type",
    "geography",
    "metric",
    "sex",
    "age",
    "stratum",
    "in_reporting_delay_period"
]

for column in categorical_columns:
    print(f"\nUnique values in '{column}':")
    print(df[column].unique())

Unique values in 'theme':
<StringArray>
['infectious_disease']
Length: 1, dtype: str

Unique values in 'sub_theme':
<StringArray>
['antimicrobial_resistance']
Length: 1, dtype: str

Unique values in 'topic':
<StringArray>
['E-coli']
Length: 1, dtype: str

Unique values in 'geography_type':
<StringArray>
['Nation']
Length: 1, dtype: str

Unique values in 'geography':
<StringArray>
['England']
Length: 1, dtype: str

Unique values in 'metric':
<StringArray>
['e-coli_testing_bacteraemiaPercentResistantRollingMonth']
Length: 1, dtype: str

Unique values in 'sex':
<StringArray>
['all']
Length: 1, dtype: str

Unique values in 'age':
<StringArray>
['all']
Length: 1, dtype: str

Unique values in 'stratum':
<StringArray>
[                       'Amikacin',                     'Carbapenems',
                   'Ciprofloxacin',                    'Co-amoxiclav',
                      'Gentamicin',    'Piperacillin with tazobactam',
 'Third Generation Cephalosporins']
Length: 7, dtype: str

Unique values in 'in_reporting_delay_period':
[False]

The categorical values are consistent with the dataset's focus on *E. coli* bloodstream infections in England. No unexpected labels were identified.

### Checking for Surrounding Whitespace

This step checks whether text values contain unnecessary spaces at the beginning or end, which could cause inconsistencies during data analysis.

In [26]:
# Check whether text columns contain leading or trailing whitespace.

text_columns = df.select_dtypes(include=["object", "string"]).columns

for column in text_columns:
    whitespace_count = (
        df[column].dropna()
        .ne(df[column].dropna().str.strip())
        .sum()
    )
    print(f"{column}: {whitespace_count} values with surrounding whitespace")

theme: 0 values with surrounding whitespace
sub_theme: 0 values with surrounding whitespace
topic: 0 values with surrounding whitespace
geography_type: 0 values with surrounding whitespace
geography: 0 values with surrounding whitespace
metric: 0 values with surrounding whitespace
sex: 0 values with surrounding whitespace
age: 0 values with surrounding whitespace
stratum: 0 values with surrounding whitespace

The check found no surrounding whitespace in the text columns, so no whitespace cleaning is required.

### Checking Date Validity

This step checks whether the dataset contains missing or invalid dates before further analysis.

In [27]:
# Check for missing and invalid dates in the dataset.

print("Missing dates:", df["date"].isna().sum())
print("Date column data type:", df["date"].dtype)
print("Earliest date:", df["date"].min())
print("Latest date:", df["date"].max())

Missing dates: 0
Date column data type: datetime64[us]
Earliest date: 2021-07-01 00:00:00
Latest date: 2026-07-01 00:00:00

The date check found no missing dates. The date column is correctly stored in datetime format, covering July 2021 to July 2026.

### Data Preparation Summary and Decision

The initial data quality checks found no missing values, duplicate records, surrounding whitespace or invalid dates. Resistance measurements were within the expected range of 0–100. The dataset will be retained for exploratory data analysis, with the date column stored in datetime format. No additional cleaning is currently indicated by these checks.

# Section 2: Exploratory Data Analysis (EDA)

Exploratory data analysis will be used to examine antibiotic resistance patterns over time and compare resistance levels across antibiotic categories. This section will use descriptive statistics and visualisations to identify trends and patterns in the dataset before developing the dashboard.

#### Ethical Considerations Before Analysis

This dataset contains aggregated national surveillance statistics rather than individual patient records, reducing privacy risks.

Differences in antibiotic resistance percentages do not explain why those differences occur. The results should not be used alone to make clinical decisions.

The dataset covers England and includes seven antibiotic categories. Findings should not be generalised beyond the information available in the dataset.

Visualisations and explanations will be presented clearly and accurately, without making assumptions about the causes of antibiotic resistance. The limitations of the dataset will be acknowledged when interpreting the results.

### Summary Statistics by Antibiotic

This analysis will summarise antibiotic resistance measurements for each antibiotic category using descriptive statistics. Comparing the mean, median, minimum and maximum values will help identify differences in resistance levels across the seven antibiotic categories.

In [28]:
# Calculate descriptive statistics for each antibiotic category
antibiotic_summary = df.groupby("stratum")["metric_value"].agg(
    ["count", "mean", "median", "min", "max"]
).round(2)

# Display the summary statistics
display(antibiotic_summary)

                                 count   mean  median    min    max
stratum
Amikacin                            61   2.76    2.82   1.52   3.61
Carbapenems                         61   0.21    0.21   0.10   0.32
Ciprofloxacin                       61  19.07   19.42  16.22  21.03
Co-amoxiclav                        61  42.69   42.70  39.64  45.51
Gentamicin                          61  11.54   11.79   9.20  13.17
Piperacillin with tazobactam        61  11.67   11.86   9.67  13.50
Third Generation Cephalosporins     61  16.04   16.02  13.22  19.10

### Initial Observations

Co-amoxiclav has the highest mean resistance value (42.69%), while carbapenems have the lowest (0.21%). Ciprofloxacin has a mean of 19.07%, followed by third-generation cephalosporins at 16.04%. All seven antibiotic categories contain 61 monthly observations.

These are descriptive findings from the dataset and do not establish why resistance levels differ. Further analysis will examine how resistance patterns change over time.

### Antibiotic Resistance Trends Over Time

A line chart will be used to examine monthly resistance patterns for all seven antibiotic categories from July 2021 to July 2026. This visualisation will help identify increases, decreases and fluctuations in resistance over time.